apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/evgeny-goldin/demo-app
  newTag: 582bb7338c17c997855fc0510524fe1796862ffb
