apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/evgeny-goldin/demo-app
  newTag: ef8741211ede63510e68f4156afc20efa97970a4
